### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by LM1LC3N7** [srounet/docker-nodebb#1]
**Hello !**

Thanks for this work !

I have a problem with persistence: plugins and database are gone when I remove my container and create a new one. But I start it with a volume..

So, how can I start your docker image with a docker volume for data persitence ?

I have already tried

``` sh
--volume=/home/nodeBB/data=/data
```

But It does not work.

**Comment by srounet** [comment]
From what I've seen, most plugins are just npm modules (see [install plugins](http://nodebb-francais.readthedocs.org/projects/nodebb/en/latest/plugins/create.html#installing-the-plugin])) so basicaly if you install a plugin, it will install it on the docker using `npm` and from there, there is no way to `backup` plugins.

Well, in fact you can, but you will have to backup the npm install folder, and from my point of view it's not clear and not what you want.

This also means, that you can modify the Dockerfile for you particular usage and add things like:

```
RUN cd /opt/nodebb && npm install nodebb-plugin-emailer-ssl-smtp
RUN cd /opt/nodebb && npm install nodebb-plugin-emailer-local
RUN cd /opt/nodebb && npm install nodebb-plugin-dbsearch
```

As for the forum data, it is stored within redis, so you should backup the redis file `/data/redis/dump.rdb`, users uploads are stored within `/data/nodebb/uploads` folder.

For general volume usage, see [docker volumes](https://docs.docker.com/engine/userguide/containers/dockervolumes/)

Is it more clear ?

**Comment by LM1LC3N7** [comment]
> Well, in fact you can, but you will have to backup the npm install folder, and from my point of view  it's not clear and not what you want.

It can work, don't you think ? Do you know what folder is it ?

Otherwise, it is more clear, thanks ! And thanks to you, I can have the latest version of NodeBB because their dockerfile isn't up-to-date.

**Comment by srounet** [comment]
> It can work, don't you think ? Do you know what folder is it ?

I think it is `/opt/nodebb/node_modules/`

> Otherwise, it is more clear, thanks ! And thanks to you, I can have the latest version of NodeBB because their dockerfile isn't up-to-date.

Yeah it isn't up-to-date, and also require a second container with redis, which I didn't wanted here.

**Comment by LM1LC3N7** [comment]
> I think it is /opt/nodebb/node_modules/

Thanks :-)

And about your single NodeBB container, it's very nice beauce it's a turnkey solution !
